name: ahamai
description: AhamAI - Your Intelligent AI Assistant.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  shared_preferences: ^2.2.0
  flutter_markdown: ^0.6.10
  http: ^1.4.0
  provider: ^6.1.2
  url_launcher: ^6.3.1
  syncfusion_flutter_pdf: ^29.1.38
  flutter_tts: ^4.2.3
  file_picker: ^10.2.0
  image_picker: ^1.1.2
  archive: ^4.0.7
  timeago: ^3.7.1
  cupertino_icons: ^1.0.8
  share_plus: ^11.0.0
  printing: ^5.14.2
  pdf: ^3.11.3
  html: ^0.15.6
  supabase_flutter: ^2.9.1
  google_mobile_ads: ^5.3.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true